version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"  # Change port mapping as needed
    depends_on:
      - db
    environment:
      - DB_URL=postgresql+asyncpg://postgres:test_password@db:5432/leads_app_db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: leads_app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: