"""update table names

Revision ID: bac38132e14e
Revises: bf99417e8f9a
Create Date: 2025-04-10 19:44:55.488639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bac38132e14e'
down_revision: Union[str, None] = 'bf99417e8f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_information', sa.String(), nullable=False),
    sa.Column('source', postgresql.ENUM('referral', 'website', 'cold_call', name='source', create_type=False), nullable=False),
    sa.Column('interest_level', postgresql.ENUM('low', 'medium', 'high', name='interestlevel', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('new', 'closed', 'qualified', name='status', create_type=False), nullable=False),
    sa.Column('assigned_salesperson_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_salesperson_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_name'), 'leads', ['name'], unique=False)
    op.drop_index('ix_lead_name', table_name='lead')
    op.drop_table('lead')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contact_information', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source', postgresql.ENUM('referral', 'website', 'cold_call', name='source'), autoincrement=False, nullable=False),
    sa.Column('interest_level', postgresql.ENUM('low', 'medium', 'high', name='interestlevel'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('new', 'closed', 'qualified', name='status'), autoincrement=False, nullable=False),
    sa.Column('assigned_salesperson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assigned_salesperson_id'], ['user.id'], name='lead_assigned_salesperson_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='lead_pkey')
    )
    op.create_index('ix_lead_name', 'lead', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.drop_index(op.f('ix_leads_name'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
